version: "3"
services:
  database:
    container_name: gcd_db
    image: postgres:12.9-alpine
    restart: always
    expose:
      - 5432
    ports:
      - 5436:5432
    env_file:
      - docker/env/db.env
    volumes:
      - ./dbdata/postgresql/lib:/var/lib/postgresql/data
  gcd:
    depends_on:
      - database
    build:
      context: .
    container_name: gcd-ca
    env_file:
      - docker/env/app.env
    ports:
      - 8099:8099
    volumes:
      - ./appdata:/data