spring:
  application:
    name: gcd
  main:
    banner-mode: "off"
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    username: gcd_u
    password: bUJfKyGtz2CseV
    maximumPoolSize: 30
    minimumIdle: 5
    dataSourceProperties:
      serverName: ${DATABASE_HOST}
      portNumber: 5432
      databaseName: gcd_db
  flyway:
    enabled: true
    locations: "classpath:db/migration"

server:
  port: 8099

open-api:
  title: gcd
  description: App for calculate GCD
  maintainerName: Alexey Okruzhko
  maintainerEmail: ao@email.com
